main: eu.metacloudservice.bukkit.BukkitBootstrap
version: 1.0.9-RELEASE
author: RauchigesEtwas
name: weapie-plugin
depend: ["metacloud-api"]
load: STARTUP

description: This plugin is managing all the background stuff
website: https://metacloudservice.eu

commands:
  service: